# Generated by Django 5.1.3 on 2024-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
