# Generated by Django 5.1.3 on 2024-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
