# Generated by Django 5.1.3 on 2024-12-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
