# Generated by Django 5.1.3 on 2024-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
