# Generated by Django 5.1.3 on 2024-12-06 11:53

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='date_entry',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 12, 7)),
        ),
    ]
