# Generated by Django 5.1.3 on 2024-12-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_timeentry_date_entry_alter_project_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion_date',
        ),
    ]
